name: Deploy Pages

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: "Deploy to Pages"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          node-version: "3.13"

      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: python -m pip install -r requirements.txt

      - name: "Build Static Content"
        run: bash build.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: new.zekro.de
